#!/bin/bash
# Session Auto Git & Notion Logger
# 새로운 세션이 열리면 자동으로 실행됩니다.

set +e

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
LOG_FILE="$HOME/.claude/session-auto.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}
# 로그 로테이션 (10000줄 초과 시 5000줄 유지)
if [ -f "$LOG_FILE" ] && [ "$(wc -l < "$LOG_FILE" 2>/dev/null)" -gt 10000 ] 2>/dev/null; then
    tail -5000 "$LOG_FILE" > "${LOG_FILE}.tmp" && mv "${LOG_FILE}.tmp" "$LOG_FILE" 2>/dev/null || true
fi

log "=== Session Started: $PROJECT_DIR ==="

# 1. Git Repository 초기화 및 Private Repo 생성
init_git_repo() {
    cd "$PROJECT_DIR" || exit 1

    if [ ! -d ".git" ]; then
        log "Initializing new Git repository..."
        git init

        # .gitignore 생성 (기본 제외 패턴)
        if [ ! -f ".gitignore" ]; then
            cat > .gitignore << 'EOF'
# OS
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
*.swo

# Environment
.env
.env.local
*.pem

# Dependencies
node_modules/
__pycache__/
*.pyc
venv/
.venv/

# Build
dist/
build/
*.egg-info/

# Logs
*.log
logs/
EOF
            log "Created .gitignore"
        fi

        # 초기 커밋
        git add -A
        git commit -m "Initial commit - Auto-generated by Claude Code Session

🤖 Generated with Claude Code Session Auto-Git" 2>/dev/null || true

        # GitHub CLI로 private repo 생성
        if command -v gh &> /dev/null; then
            REPO_NAME=$(basename "$PROJECT_DIR")

            # 이미 remote가 있는지 확인
            if ! git remote get-url origin &> /dev/null; then
                log "Creating private GitHub repository: $REPO_NAME"

                # private repo 생성 및 push
                if gh repo create "$REPO_NAME" --private --source=. --remote=origin --push 2>/dev/null; then
                    log "SUCCESS: Private repository created and pushed"
                else
                    log "Repository may already exist, trying to set remote..."
                    GH_USER=$(gh api user --jq '.login' 2>/dev/null)
                    if [ -n "$GH_USER" ]; then
                        git remote add origin "https://github.com/$GH_USER/$REPO_NAME.git" 2>/dev/null || true
                        git push -u origin main 2>/dev/null || git push -u origin master 2>/dev/null || true
                    fi
                fi
            else
                log "Remote origin already exists, pushing changes..."
                git push 2>/dev/null || true
            fi
        else
            log "WARNING: GitHub CLI (gh) not installed. Skipping remote setup."
        fi
    else
        log "Git repository already exists"
        # 기존 repo가 있으면 상태만 확인
        if git remote get-url origin &> /dev/null; then
            log "Remote: $(git remote get-url origin)"
        fi
    fi
}

# 2. Notion에 세션 시작 기록 (프로젝트별 하위 페이지)
log_to_notion() {
    if [ -n "$NOTION_API_KEY" ]; then
        log "Logging session start to Notion..."

        PROJECT_NAME=$(basename "$PROJECT_DIR")

        # 새로운 advanced 로거 사용 (프로젝트별 페이지)
        if [ -f "$HOME/claude/TP_skills/session-manager/notion-advanced.py" ]; then
            python3 "$HOME/claude/TP_skills/session-manager/notion-advanced.py" \
                "$PROJECT_NAME" \
                "Session Started" \
                "Path: $PROJECT_DIR" \
                2>/dev/null && log "Notion logged successfully" || log "Notion logging failed"
        elif [ -f "$HOME/.claude/hooks/notion-logger.py" ]; then
            # 폴백: 기본 로거
            python3 "$HOME/.claude/hooks/notion-logger.py" \
                "Session Started" \
                "Project: $PROJECT_DIR" \
                2>/dev/null && log "Notion logged (basic)" || log "Notion logging failed"
        fi
    else
        log "Notion API not configured (NOTION_API_KEY missing)"
    fi
}

# 3. 주간 데이터 소비 요약 (매 세션 시작 시)
weekly_summary() {
    local STALE_LOG="$HOME/.claude/logs/stale_warnings.jsonl"
    local IMPACT_LOG="$HOME/.claude/logs/cross-impact.jsonl"
    local RALPH_DIR="$HOME/claude/TP_history/_global/ralph-reports"

    local stale_count=0
    local impact_count=0
    local ralph_count=0

    # stale 경고 지난 7일 집계
    if [ -f "$STALE_LOG" ]; then
        stale_count=$(_SS_STALE="$STALE_LOG" python3 -c "
import json, datetime, os
cutoff = (datetime.datetime.now() - datetime.timedelta(days=7)).isoformat()
count = 0
try:
  with open(os.environ['_SS_STALE']) as f:
    for line in f:
      try:
        e = json.loads(line.strip())
        if e.get('timestamp','') >= cutoff:
          count += 1
      except: pass
except: pass
print(count)
" 2>/dev/null || echo "0")
    fi

    # ralph 보고서 미확인 건수 (지난 7일)
    if [ -d "$RALPH_DIR" ]; then
        ralph_count=$(find "$RALPH_DIR" -name "*.md" -newer "$HOME/.claude/logs/last-review.flag" 2>/dev/null | wc -l | tr -d ' ')
    fi

    # 크로스 임팩트 지난 7일
    if [ -f "$IMPACT_LOG" ]; then
        impact_count=$(env _SS_LOG="$IMPACT_LOG" _SS_PROJ="$(basename "$PROJECT_DIR")" python3 -c "
import json, datetime, os
cutoff = (datetime.datetime.now() - datetime.timedelta(days=7)).isoformat()
project = os.environ['_SS_PROJ']
count = 0
try:
  with open(os.environ['_SS_LOG']) as f:
    for line in f:
      try:
        e = json.loads(line.strip())
        if e.get('timestamp','') >= cutoff and e.get('source_project','') != project:
          count += 1
      except: pass
except: pass
print(count)
" 2>/dev/null || echo "0")
    fi

    # 요약 출력 (하나라도 있을 때만)
    if [ "$stale_count" -gt 0 ] || [ "$ralph_count" -gt 0 ] || [ "$impact_count" -gt 0 ]; then
        echo "┌─ [M+N 주간 요약 / 지난 7일]"
        [ "$stale_count" -gt 0 ] && echo "│  📋 stale 경고 ${stale_count}건 — ~/.claude/logs/stale_warnings.jsonl"
        [ "$ralph_count" -gt 0 ] && echo "│  📄 ralph 보고서 ${ralph_count}건 미확인 — TP_history/_global/ralph-reports/"
        [ "$impact_count" -gt 0 ] && echo "│  🔗 크로스 프로젝트 변경 ${impact_count}건 — ~/.claude/logs/cross-impact.jsonl"
        echo "└─────────────────────────────"
    fi

    # 마지막 리뷰 플래그 갱신
    touch "$HOME/.claude/logs/last-review.flag" 2>/dev/null || true
}

# 실행
init_git_repo
log_to_notion
weekly_summary

log "=== Session setup complete ==="
exit 0
